language: node_js
node_js: '12'

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

install:
  - yarn --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: 'Lint'
      name: 'Lint'
      script:
        - yarn lint

    - stage: 'Test unit and  e2e'
      name: 'Test'
      before_script:
        - yarn global add codecov && wait-on http://localhost:8080
      script:
        - yarn test:e2e
      after_script:
        - codecov
