language: node_js
node_js: '12'

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

install:
  - yarn --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: 'Lint'
      name: 'Lint'
      script:
        - yarn lint
    - stage: 'Test unit'
      name: 'Test'
      script:
        - yarn test:unit
    - stage: 'E2E testing'
      name: 'Test'
      script:
        - yarn test:e2e
