language: node_js
node_js: '12'

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

install:
  - yarn --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: 'Lint'
      name: 'Lint'
      script:
        - yarn lint
    - stage: 'Test unit'
      name: 'Test Unit'
      script:
        - yarn test:unit
    - stage: 'E2E testing'
      name: 'Test Cypress'
      script:
        - yarn test:e2e
    - stage: 'Deploy'
      name: 'Deploy app'
      before_script:
        - yarn build
      skip_cleanup: true
      provider: firebase
      token:
        secure: ""
