language: node_js
node_js: '12'

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

install:
  - yarn --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: 'Lint'
      name: 'Lint'
      script:
        - yarn lint
    - stage: 'Test unit'
      name: 'Test Unit'
      script:
        - yarn test:unit
    - stage: 'E2E testing'
      name: 'Test Cypress'
      script:
        - yarn test:e2e
    - stage: 'Build and Deloy'
      name: 'Build app'
      script:
        - yarn build
      after_success:
        - cd packages/web/login-admin
        - npm install -g firebase-tools
        - firebase deploy --token "$FIREBASE_TOKEN"
